name: Publish Release Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db:
          - name: mysql
            suffix: ""
          - name: postgres
            suffix: -postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract release info
        id: release_info
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "IS_PRERELEASE=${{ github.event.release.prerelease }}" >> $GITHUB_ENV

      - name: Build and tag image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}${{ matrix.db.suffix }}
          docker build -t $IMAGE:${{ env.RELEASE_TAG }} . --build-arg DB_TYPE=${{ matrix.db.name }}

          if [ "${{ env.IS_PRERELEASE }}" = "true" ]; then
            docker tag $IMAGE:${{ env.RELEASE_TAG }} $IMAGE:beta
            docker push $IMAGE:beta
          else
            docker tag $IMAGE:${{ env.RELEASE_TAG }} $IMAGE:latest
            docker push $IMAGE:latest
          fi

          docker push $IMAGE:${{ env.RELEASE_TAG }}

  send-discord:
    needs: build-and-push
    uses: ./.github/workflows/discord-changelog.yml
    secrets: inherit
